export enum ActionTypes {

  NETWORK_FAILURE = 'NETWORK_FAILURE',

  USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST',
  USER_LOGIN_REQUEST_SUCCESS = 'USER_LOGIN_REQUEST_SUCCESS',
  USER_LOGIN_REQUEST_FAILURE = 'USER_LOGIN_REQUEST_FAILURE',

  MESSAGE_SEND_REQUEST = 'MESSAGE_SEND_REQUEST',
  MESSAGE_SEND_REQUEST_SUCCESS = 'MESSAGE_SEND_REQUEST_SUCCESS',

  MESSAGE_LIST_UPDATE = 'MESSAGE_LIST_UPDATE',
  MESSAGE_REFRESH_REQUEST = 'MESSAGE_REFRESH_REQUEST',

  PHOTO_LIST_UPDATE = 'PHOTO_LIST_UPDATE',
  PHOTO_REFRESH_REQUEST = 'PHOTO_REFRESH_REQUEST',

  PHOTO_PUBLISH_REQUEST = 'PHOTO_PUBLISH_REQUEST',
  PHOTO_PUBLISH_REQUEST_SUCCESS = 'PHOTO_PUBLISH_REQUEST_SUCCESS',

  PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST',
  PROFILE_CREATE_REQUEST_SUCCESS = 'PROFILE_CREATE_REQUEST_SUCCESS',
  PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST',
  PROFILE_UPDATE_REQUEST_SUCCESS = 'PROFILE_UPDATE_REQUEST_SUCCESS',

}

export interface AppAction<P> {
  type: ActionTypes;
  payload: P;
}
